version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: rag_backend
    ports:
      - "8000:8000"
    volumes:
      - ./agents:/app/agents
      - ./parsing_chunks:/app/parsing_chunks
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: rag_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - FASTAPI_URL=http://backend:8000
